name: actions
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - ATTRIBUTIONS.md
      - '.github/workflows/codeql-analysis.yaml'
      - '.github/dependabot.yaml'
    branches:
      - root
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE.md
      - ATTRIBUTIONS.md
      - '.github/workflows/codeql-analysis.yaml'
      - '.github/dependabot.yaml'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0
      - run: Get-ChildItem -Force
      - name: Run action
        uses: ./
        id: jjversion
      - name: Display jjversion outputs
        run: |
          echo "Major: ${{ steps.jjversion.outputs.major }}"
          echo "Minor: ${{ steps.jjversion.outputs.minor }}"
          echo "Patch: ${{ steps.jjversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.jjversion.outputs.majorMinorPatch }}"
          echo "Sha: ${{ steps.jjversion.outputs.sha }}"
          echo "ShortSha: ${{ steps.jjversion.outputs.shortSha }}"

  test-skip-input:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: test-skip-input
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0
      - run: Get-ChildItem -Force
      - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613
      - name: Run action
        uses: ./
        with:
          skip-go-installation: true
        id: jjversion
      - name: Display jjversion outputs
        run: |
          echo "Major: ${{ steps.jjversion.outputs.major }}"
          echo "Minor: ${{ steps.jjversion.outputs.minor }}"
          echo "Patch: ${{ steps.jjversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.jjversion.outputs.majorMinorPatch }}"
          echo "Sha: ${{ steps.jjversion.outputs.sha }}"
          echo "ShortSha: ${{ steps.jjversion.outputs.shortSha }}"

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0
      - run: git log --oneline
      - name: Run action
        uses: ./
        with:
          skip-go-installation: true
        id: jjversion
      - run: echo "VERSION=$(echo ${{ steps.jjversion.outputs.majorMinorPatch }})" >> $GITHUB_ENV
      - run: git reset --soft HEAD~1
      - name: Run action for previous commit version
        uses: ./
        with:
          skip-go-installation: true
        id: previousversion
      - run: echo "PREVIOUS_COMMIT_VERSION=$(echo ${{ steps.previousversion.outputs.majorMinorPatch }})" >> $GITHUB_ENV
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          repository: jjliggett/jjversion
          ref: 8d5c529715bc9d90834e0bd1a7ec472181eaf05f
          path: jjversion-core
          clean: false
      - run: ls -R
      - run: go build -a -v -o jjversion-ghao-${{ env.VERSION }}-linux-x64/jjversion-ghao
      - run: env GOOS=darwin GOARCH=amd64 go build -a -v -o jjversion-ghao-${{ env.VERSION }}-darwin-amd64/jjversion-ghao-darwin
      - run: env GOOS=windows GOARCH=amd64 go build -a -v -o jjversion-ghao-${{ env.VERSION }}-windows-x64/jjversion-ghao.exe
      - run: mkdir docs-and-licenses
      - run: cp README.md docs-and-licenses
      - run: cp LICENSE.md docs-and-licenses
      - run: cp ATTRIBUTIONS.md docs-and-licenses
      - run: cp jjversion-core/README.md docs-and-licenses/jjversion-core-README.md
      - run: cp jjversion-core/LICENSE.md docs-and-licenses/jjversion-core-LICENSE.md
      - run: cp jjversion-core/docs/ATTRIBUTIONS.md docs-and-licenses/jjversion-core-ATTRIBUTIONS.md
      - run: mkdir docs-and-licenses/attributions
      - run: cp -R jjversion-core/docs/attributions/. docs-and-licenses/attributions
      - run: zip -r jjversion-ghao-docs-and-licenses-${{ env.VERSION }}.zip docs-and-licenses
      - run: ls -R
      - name: Upload jjversion-ghao
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: jjversion-ghao
          path: jjversion-ghao-${{ env.VERSION }}-linux-x64/jjversion-ghao
      - name: Upload jjversion-ghao-darwin
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: jjversion-ghao-darwin
          path: jjversion-ghao-${{ env.VERSION }}-darwin-amd64/jjversion-ghao-darwin
      - name: Upload jjversion-ghao-darwin
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: jjversion-ghao.exe
          path: jjversion-ghao-${{ env.VERSION }}-windows-x64/jjversion-ghao.exe
      - name: Upload docs
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: jjversion-ghao-docs-and-licenses-${{ env.VERSION }}.zip
          path: jjversion-ghao-docs-and-licenses-${{ env.VERSION }}.zip
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
        if: ${{ github.ref == 'refs/heads/root' && env.VERSION != env.PREVIOUS_COMMIT_VERSION }}
        with:
          repo_token: ${{ secrets.RELEASES_TOKEN }}
          automatic_release_tag: v${{ env.VERSION }}
          prerelease: false
          files: |
            jjversion-ghao-${{ env.VERSION }}-linux-x64/jjversion-ghao
            jjversion-ghao-${{ env.VERSION }}-darwin-amd64/jjversion-ghao-darwin
            jjversion-ghao-${{ env.VERSION }}-windows-x64/jjversion-ghao.exe
            README.md
            LICENSE.md
            jjversion-ghao-docs-and-licenses-${{ env.VERSION }}.zip
